IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'AuthDb')
BEGIN
    CREATE DATABASE AuthDb;
END
GO

USE AuthDb;

DROP TABLE IF EXISTS UsersAndRoles;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Roles;

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(255) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    IsVerified BIT NOT NULL DEFAULT 0,
    RefreshToken NVARCHAR(500) NULL,
    RefreshTokenExpirationUTC DATETIME2 NULL,
    SecurityStamp DATETIME2 NULL
);

CREATE TABLE Roles (
    RoleName NVARCHAR(100) PRIMARY KEY,
    RoleDescription NVARCHAR(500) NULL
);

CREATE TABLE UsersAndRoles (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL,
    RoleName NVARCHAR(100) NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (RoleName) REFERENCES Roles(RoleName) ON DELETE CASCADE
);